services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3352:3352"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_API_URL: ${NEXT_PUBLIC_BASE_API_URL:-http://localhost:3352}
        NEXT_PUBLIC_BASE_FRONTEND_URL: ${NEXT_PUBLIC_BASE_FRONTEND_URL:-http://localhost:3000}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_API_URL=${NEXT_PUBLIC_BASE_API_URL:-http://localhost:3352}
      - NEXT_PUBLIC_BASE_FRONTEND_URL=${NEXT_PUBLIC_BASE_FRONTEND_URL:-http://localhost:3000}
    depends_on:
      - backend
    restart: unless-stopped
